# Generated by Django 3.0.2 on 2021-03-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_type',
        ),
        migrations.AddField(
            model_name='answers',
            name='correct_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='correct_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='correct_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='correct_d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Quiz'),
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Quiz'),
        ),
    ]
