# Generated by Django 3.0.2 on 2021-03-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210310_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='quiz',
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Questions'),
        ),
    ]
