# Generated by Django 3.0.2 on 2021-03-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210310_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='answer_d',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='correct_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='correct_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='correct_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='correct_d',
            field=models.BooleanField(default=False),
        ),
    ]
