# Generated by Django 3.0.2 on 2021-03-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210315_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_a', models.BooleanField(default=False)),
                ('answer_b', models.BooleanField(default=False)),
                ('answer_c', models.BooleanField(default=False)),
                ('answer_d', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Participant')),
            ],
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
