# Generated by Django 3.0.2 on 2021-03-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210315_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantanswers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_answer', to='api.Questions'),
        ),
    ]
