# Generated by Django 3.0.2 on 2021-03-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_participantanswers_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='groupwork',
            field=models.BooleanField(default=False),
        ),
    ]
