# Generated by Django 3.0.2 on 2021-03-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210321_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='wait_on_submit',
            field=models.BooleanField(default=True),
        ),
    ]
