# Generated by Django 3.0.2 on 2021-03-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_quiz_wait_on_submit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='wait_on_submit',
            new_name='host_control',
        ),
    ]
