# Generated by Django 3.0.2 on 2021-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210328_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='load_next',
            field=models.BooleanField(default=True),
        ),
    ]
