# Generated by Django 3.0.2 on 2021-04-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_questions_load_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='groupwork',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='host_control',
            field=models.BooleanField(default=False),
        ),
    ]
