# Generated by Django 3.0.2 on 2021-04-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210407_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_num',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
